CREATE DATABASE IF NOT EXISTS inventory_database CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE inventory_database;

DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS periods;

CREATE TABLE periods (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    month VARCHAR(7) NOT NULL UNIQUE,
    status ENUM("OPEN", "CLOSED") NOT NULL DEFAULT "OPEN",
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB;

CREATE TABLE items (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    period_id INT UNSIGNED NOT NULL,
    barcode VARCHAR(20) NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    category ENUM("ATK", "Kebersihan", "Pantry", "Lainya") NOT NULL,
    unit VARCHAR(30) NOT NULL,
    quantity INT NOT NULL DEFAULT 0,
    stock INT NOT NULL DEFAULT 0,
    price DECIMAL(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_items_period FOREIGN KEY (period_id) REFERENCES periods (id) ON DELETE CASCADE,
    INDEX idx_items_period_barcode (period_id, barcode)
) ENGINE=InnoDB;